sudo: false
language: node_js
branches:
  only:
    - master
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - node_modules
before_script:
  - npm install -g npm@latest
install:
  - npm install
script:
  - npm test
  - npm run build
